#line 2 "cool-lex.cc"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define FLEX_DEBUG
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;

#define FLEX_DEBUG
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
static yyconst short int yy_accept[187] =
    {   0,
        0,    0,    0,    0,    4,    4,    0,    0,    0,    0,
       61,   59,    2,    1,   40,    6,    6,    6,    6,   18,
        6,    6,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   11,   14,   12,   13,    4,    5,
       52,   42,   41,   43,   49,   57,   54,   53,   58,    2,
        7,    8,    3,   18,   17,   16,   15,   38,   38,   38,
       38,   38,   23,   24,   25,   38,   38,   38,   38,   38,
       32,   38,   38,   38,   39,   39,   39,   39,   39,   39,
       23,   24,   25,   39,   39,   39,   39,   39,   32,   39,

       39,   39,   39,   11,    9,   10,    4,   52,   50,   51,
       46,   47,   44,   45,   48,   57,   55,   56,   38,   38,
       38,   38,   38,   38,   28,   38,   30,   31,   38,   38,
       38,   39,   39,   39,   39,   39,   39,   39,   28,   39,
       30,   31,   39,   39,   39,   39,   19,   38,   21,   22,
       38,   38,   29,   33,   34,   38,   19,   39,   21,   22,
       39,   39,   39,   29,   33,   34,   35,   39,   20,   38,
       38,   37,   20,   36,   39,   39,   37,   38,   27,   39,
       27,   38,   39,   26,   26,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    5,
        6,    7,    8,    8,    9,    8,    8,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    8,    8,   11,
       12,   13,    1,    8,   14,   15,   16,   17,   18,   19,
       15,   20,   21,   15,   15,   22,   15,   23,   24,   25,
       15,   26,   27,   28,   29,   30,   31,   15,   15,   15,
        1,   32,    1,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   40,   40,   43,   40,   44,
       45,   46,   40,   47,   48,   49,   50,   51,   52,   40,
       40,   40,    8,    1,    8,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    2,    3,    4,    1,    4,    1,    1,    5,
        1,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    3,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    6
    } ;

static yyconst short int yy_base[199] =
    {   0,
        0,    0,   51,   52,  285,  284,   57,   59,   61,   63,
      273,  365,  196,  365,  365,  179,  365,  152,  115,  111,
       59,  104,    0,   56,   53,   52,   58,   80,   85,   53,
       55,   64,   66,    0,   94,   92,   99,  115,  108,  126,
       92,   91,  119,  102,    0,  365,   81,   81,    0,  365,
        0,  365,  365,  126,  365,    0,  365,  365,   80,   80,
      365,  365,  365,   66,  365,  365,  365,    0,  100,  133,
      124,  135,    0,    0,  132,  125,  128,  133,  131,  140,
        0,  150,  162,  160,    0,  155,  170,  158,  173,  166,
        0,    0,  170,  161,  164,  169,  163,  168,    0,  173,

      181,  172,  184,    0,  365,  365,    0,    0,  365,  365,
      365,  365,  365,  365,  365,    0,  365,  365,  190,  183,
      198,  204,  203,  199,    0,  199,    0,    0,  203,  204,
      207,  214,  203,  215,  218,  208,  219,  214,    0,  214,
        0,    0,  220,  220,  229,  227,    0,  228,    0,    0,
      232,  240,    0,    0,    0,  247,    0,  235,    0,    0,
      248,  242,  248,    0,    0,    0,    0,  253,    0,  251,
      257,    0,    0,    0,  254,  260,    0,  250,    0,  252,
        0,  254,  257,    0,    0,  365,  305,  311,  317,  323,
       69,   64,  329,  335,  341,  346,  352,  358

    } ;

static yyconst short int yy_def[199] =
    {   0,
      186,    1,  187,  187,  188,  188,  189,  189,  190,  190,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  193,  186,  186,  186,  194,  186,
      195,  186,  186,  196,  186,  197,  186,  186,  198,  186,
      186,  186,  186,  186,  186,  186,  186,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,

      192,  192,  192,  193,  186,  186,  194,  195,  186,  186,
      186,  186,  186,  186,  186,  197,  186,  186,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  191,  191,
      191,  191,  192,  192,  192,  192,  192,  191,  191,  192,
      192,  191,  192,  191,  192,    0,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186

    } ;

static yyconst short int yy_nxt[419] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   17,   19,   20,
       21,   22,   12,   23,   23,   24,   23,   25,   26,   23,
       27,   28,   29,   30,   31,   23,   23,   32,   23,   23,
       33,   12,   12,   34,   34,   35,   34,   36,   37,   34,
       34,   38,   39,   40,   41,   42,   34,   34,   43,   34,
       34,   44,   12,   46,   46,   47,   47,   48,   48,   52,
       53,   52,   53,   57,   58,   57,   58,   65,   85,   69,
       66,   81,   73,   68,   71,   64,   74,   70,   82,   72,
       75,   60,  118,   83,   76,   84,  106,  105,   54,   69,
       54,   81,   59,   73,   59,   71,   74,   77,   70,   82,

       72,   75,   79,   78,   83,   76,   84,   86,   80,   55,
       99,   55,   90,   88,  100,   87,   67,   77,   89,   91,
       64,  103,   79,   63,   78,   95,  119,   86,  110,   80,
       99,   96,   90,   92,   88,  100,   87,   93,  101,   89,
       91,   94,  103,   97,  102,   95,  120,  119,  122,   98,
      121,  123,   96,   92,  124,  125,  126,   62,   93,  101,
      111,  127,   94,   97,  112,  102,  120,  128,  122,  113,
       98,  121,  123,  129,  114,  124,  125,  126,  115,  130,
      131,  132,  127,  133,  134,   61,  135,  136,  128,  137,
      138,  139,  140,  141,  129,  142,  143,   60,  144,  130,

      145,  131,  132,  133,  146,  134,  135,  147,  136,  148,
      137,  138,  139,  140,  141,  149,  142,  143,  144,  150,
      151,  145,  152,  153,  154,  146,  155,  147,  156,  158,
      148,  157,  159,  160,  161,  149,  162,  163,  164,  150,
      151,  165,  166,  152,  153,  154,  167,  155,  168,  156,
      158,  157,  159,  160,  169,  161,  162,  170,  163,  164,
      171,  173,  165,  166,  172,  174,  167,  175,  176,  168,
      177,  178,  186,  179,  180,  169,  181,  182,  170,  183,
      184,  171,  173,  185,  172,  174,   50,   50,  175,  176,
      177,  186,  178,  179,  186,  180,  181,  186,  182,  186,

      183,  184,  186,  186,  185,   45,   45,   45,   45,   45,
       45,   49,   49,   49,   49,   49,   49,   51,   51,   51,
       51,   51,   51,   56,   56,   56,   56,   56,   56,  104,
      186,  104,  186,  104,  104,  107,  186,  107,  107,  107,
      107,  108,  186,  186,  108,  108,  109,  109,  109,  109,
      109,  109,  116,  186,  186,  116,  116,  116,  117,  117,
      117,  117,  117,  117,   11,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,

      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186
    } ;

static yyconst short int yy_chk[419] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    3,    4,    3,    4,    7,
        7,    8,    8,    9,    9,   10,   10,   21,  192,   24,
       21,   30,   26,  191,   25,   64,   27,   24,   31,   25,
       27,   60,   59,   32,   27,   33,   48,   47,    7,   24,
        8,   30,    9,   26,   10,   25,   27,   28,   24,   31,

       25,   27,   29,   28,   32,   27,   33,   35,   29,    7,
       41,    8,   37,   36,   42,   35,   22,   28,   36,   37,
       20,   44,   29,   19,   28,   39,   69,   35,   54,   29,
       41,   39,   37,   38,   36,   42,   35,   38,   43,   36,
       37,   38,   44,   40,   43,   39,   70,   69,   72,   40,
       71,   75,   39,   38,   76,   77,   78,   18,   38,   43,
       54,   79,   38,   40,   54,   43,   70,   80,   72,   54,
       40,   71,   75,   82,   54,   76,   77,   78,   54,   83,
       84,   86,   79,   87,   88,   16,   89,   90,   80,   93,
       94,   95,   96,   97,   82,   98,  100,   13,  101,   83,

      102,   84,   86,   87,  103,   88,   89,  119,   90,  120,
       93,   94,   95,   96,   97,  121,   98,  100,  101,  122,
      123,  102,  124,  126,  129,  103,  130,  119,  131,  133,
      120,  132,  134,  135,  136,  121,  137,  138,  140,  122,
      123,  143,  144,  124,  126,  129,  145,  130,  146,  131,
      133,  132,  134,  135,  148,  136,  137,  151,  138,  140,
      152,  158,  143,  144,  156,  161,  145,  162,  163,  146,
      168,  170,   11,  171,  175,  148,  176,  178,  151,  180,
      182,  152,  158,  183,  156,  161,    6,    5,  162,  163,
      168,    0,  170,  171,    0,  175,  176,    0,  178,    0,

      180,  182,    0,    0,  183,  187,  187,  187,  187,  187,
      187,  188,  188,  188,  188,  188,  188,  189,  189,  189,
      189,  189,  189,  190,  190,  190,  190,  190,  190,  193,
        0,  193,    0,  193,  193,  194,    0,  194,  194,  194,
      194,  195,    0,    0,  195,  195,  196,  196,  196,  196,
      196,  196,  197,    0,    0,  197,  197,  197,  198,  198,
      198,  198,  198,  198,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,

      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst short int yy_rule_linenum[60] =
    {   0,
      104,  105,  106,  108,  109,  113,  119,  122,  128,  129,
      134,  135,  136,  138,  150,  151,  152,  153,  161,  162,
      163,  164,  165,  166,  167,  168,  171,  172,  173,  174,
      175,  176,  177,  178,  179,  181,  183,  185,  188,  201,
      204,  219,  238,  245,  246,  247,  248,  250,  256,  262,
      263,  269,  287,  292,  304,  305,  307,  309,  313
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cool.flex"
#define INITIAL 0
/*
  The scanner definition for COOL.
*/
#line 5 "cool.flex"
/*
   See copyright.h for copyright notice, limitation of liability,
   and disclaimer of warranty provisions.

   sm 1/27/01:  I have made a rather significant change to PA2:
   We now do *not* require students to collect consecutive error
   characters (instead they are now reported one at a time).
   The ostensible rationale for this requirement was
   that it provides a little experience dealing with the nitty-
   gritty reality of these tools.  However, it has these problems:
     - it offers no diagnostic value
     - can't use '.' to mean "everything else"
     - unfair to C++ students since C makes it difficult to
       put NULL inside strings
     - malloc/etc is so much hacking (since only soln to encoding
       is to collect piecewise)
     - encoding problem means c/java have diff't output
   Therefore I have changed the code below.  I removed quite a bit
   of mechanism.  If one wants to get it back, get a version out of
   CVS that is earlier than 1/27/01.
*/
#include "copyright.h"

#include "cool-parse.h"
#include "stringtab.h"
#include "utilities.h"

/* The compiler assumes these identifiers. */
#define yylval cool_yylval
#define yylex  cool_yylex

/* Max size of string constants */
#define MAX_STR_CONST 1025
#define YY_NO_UNPUT   /* keep g++ happy */
#define yywrap() 1
#define YY_SKIP_YYWRAP

/*
 *   The check is applied before we add characters to the buffer.
 */
#define check_string_overflow \
  if (string_buf_ptr - string_buf >= MAX_STR_CONST) { \
    yylval.error_msg = "String constant too long";  \
    BEGIN(STRING_RECOVER); \
    return (ERROR); }

extern FILE *fin; /* we read from this file */

/* define YY_INPUT so we read from the FILE fin:
 * This change makes it possible to use this scanner in
 * the Cool compiler.
 */
#undef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread( (char*)buf, sizeof(char), max_size, fin)) < 0) \
		YY_FATAL_ERROR( "read() in flex scanner failed");

char string_buf[MAX_STR_CONST]; /* to assemble string constants */
char *string_buf_ptr;
                               
/* buffer for returning single bad characters, always
 * guaranteed to have a \0 in the 2nd slot */
char bad_char_buf[2] = { 0,0 };

extern int curr_lineno;
extern int verbose_flag;

extern YYSTYPE cool_yylval;

/* added {} to single and illegal, JDD 8/16/96 */
/* \0 is removed from illegal because it requires special handling */
#define COMMENT 1

#define LINE_COMMENT 2

#define STRING 3

/* To recover from overly long string constants */
#define STRING_RECOVER 4

/* sm: automatically report coverage holes */
#line 622 "cool-lex.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 99 "cool.flex"


	int comment_nesting = 0; /* Keep track of nesting level in comments */


#line 779 "cool-lex.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 187 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 365 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */

		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 60 )
				fprintf( stderr, "--accepting rule at line %d (\"%s\")\n",
				         yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 60 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 61 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 104 "cool.flex"
curr_lineno++;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 105 "cool.flex"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 106 "cool.flex"
{ BEGIN(LINE_COMMENT); }
	YY_BREAK

case 4:
YY_RULE_SETUP
#line 108 "cool.flex"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 109 "cool.flex"
{ BEGIN(INITIAL); curr_lineno++; }
	YY_BREAK
case YY_STATE_EOF(LINE_COMMENT):
#line 110 "cool.flex"
{ BEGIN(INITIAL); }
	YY_BREAK

case 6:
YY_RULE_SETUP
#line 113 "cool.flex"
{ return (*yytext); }
	YY_BREAK
/*
  *  Nested comments
  */
case 7:
YY_RULE_SETUP
#line 119 "cool.flex"
{ BEGIN(COMMENT);
			  comment_nesting++;
			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 122 "cool.flex"
{ /* error - unmatched comment */
			  yylval.error_msg = "Unmatched *)";
			  return (ERROR);
                	}
	YY_BREAK

case 9:
YY_RULE_SETUP
#line 128 "cool.flex"
comment_nesting++;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 129 "cool.flex"
{ comment_nesting--;
		  if (comment_nesting == 0)
			BEGIN(INITIAL);
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 134 "cool.flex"
/* eat anything that's not a '*', '(', or '\n' */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 135 "cool.flex"
/* eat up other '('s */
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 136 "cool.flex"
/* eat up other '*'s */
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 138 "cool.flex"
curr_lineno++;
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 140 "cool.flex"
{ /* error - unterminated comment */
		  yylval.error_msg = "EOF in comment";
		  BEGIN(INITIAL);
		  return (ERROR);
               	}
	YY_BREAK

/*
  *  The multiple-character operators.
  */
case 15:
YY_RULE_SETUP
#line 150 "cool.flex"
{ return (DARROW); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 151 "cool.flex"
{ return (LE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 152 "cool.flex"
{ return (ASSIGN); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 153 "cool.flex"
{ yylval.symbol = inttable.add_string(yytext,yyleng);
		  return (INT_CONST); }
	YY_BREAK
/*
  * Keywords are case-insensitive except for the values true and false,
  * which must begin with a lower-case letter.
  */
case 19:
YY_RULE_SETUP
#line 161 "cool.flex"
{ return (CASE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 162 "cool.flex"
{ return (CLASS); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 163 "cool.flex"
{ return (ELSE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 164 "cool.flex"
{ return (ESAC); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 165 "cool.flex"
{ return (FI); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 166 "cool.flex"
{ return (IF); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 167 "cool.flex"
{ return (IN); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 168 "cool.flex"
{ return (INHERITS); }
	YY_BREAK
/* [Ii][Ss]  			{ return (IS); } */
case 27:
YY_RULE_SETUP
#line 171 "cool.flex"
{ return (ISVOID); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 172 "cool.flex"
{ return (LET); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 173 "cool.flex"
{ return (LOOP); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 174 "cool.flex"
{ return (NEW); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 175 "cool.flex"
{ return (NOT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 176 "cool.flex"
{ return (OF); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 177 "cool.flex"
{ return (POOL); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 178 "cool.flex"
{ return (THEN); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 179 "cool.flex"
{ yylval.boolean = 1;
                  		  return (BOOL_CONST); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 181 "cool.flex"
{ yylval.boolean = 0;
				  return (BOOL_CONST); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 183 "cool.flex"
{ return (WHILE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 185 "cool.flex"
{ yylval.symbol = idtable.add_string(yytext, yyleng); 
		  return (TYPEID); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 188 "cool.flex"
{ yylval.symbol = idtable.add_string(yytext, yyleng); 
		  return (OBJECTID); }
	YY_BREAK
/*
  *  String constants (C syntax, taken from lexdoc(1) )
  *  Escape sequence \c is accepted for all characters c. Except for 
  *  \n \t \b \f, the result is c.
  *  (but note that 'c' can't be the NUL character)
  *
  */
case 40:
YY_RULE_SETUP
#line 201 "cool.flex"
string_buf_ptr = string_buf; BEGIN(STRING);
	YY_BREAK

case 41:
YY_RULE_SETUP
#line 204 "cool.flex"
{
		  /* saw closing quote - all done */

          BEGIN(INITIAL);
	  if (string_buf_ptr - string_buf >= MAX_STR_CONST)
	  {
	    yylval.error_msg = "String constant too long";
	    return (ERROR);
	  }
          *string_buf_ptr = '\0';
	  yylval.symbol = 
          stringtable.add_string(string_buf,MAX_STR_CONST);
	  return (STR_CONST);
        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 219 "cool.flex"
{
          /* error - unterminated string constant */
          /* generate error message */

	  curr_lineno++;
	  yylval.error_msg = "Unterminated string constant";
	  BEGIN(INITIAL);
	  return (ERROR);
        }
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 229 "cool.flex"
{
          /* error - unterminated string constant */
          /* generate error message */

	  yylval.error_msg = "EOF in string constant";
	  BEGIN(INITIAL);
	  return (ERROR);
        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 238 "cool.flex"
{
	  /* matches only if "\" is the last character in the file.*/
	  yylval.error_msg = "backslash at end of file";
	  BEGIN(INITIAL);
	  return (ERROR);
        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 245 "cool.flex"
{ check_string_overflow; *string_buf_ptr++ = '\n'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 246 "cool.flex"
{ check_string_overflow; *string_buf_ptr++ = '\t'; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 247 "cool.flex"
{ check_string_overflow; *string_buf_ptr++ = '\b'; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 248 "cool.flex"
{ check_string_overflow; *string_buf_ptr++ = '\f'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 250 "cool.flex"
{
	  yylval.error_msg = "String contains escaped null character.";
	  BEGIN(STRING_RECOVER);
	  return(ERROR);
        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 256 "cool.flex"
{
	  yylval.error_msg = "String contains null character.";
	  BEGIN(STRING_RECOVER);
	  return(ERROR);
        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 262 "cool.flex"
{ check_string_overflow; *string_buf_ptr++ = yytext[1]; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 263 "cool.flex"
{ curr_lineno++;
		  check_string_overflow;
		  *string_buf_ptr++ = yytext[1];
		}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 269 "cool.flex"
{
                  char *tmp_ptr = yytext;

		  if (string_buf_ptr + yyleng - string_buf >
		      MAX_STR_CONST)
		  {
	            /* Discard previous part of string */
		    string_buf_ptr = string_buf;
		    yylval.error_msg = "String constant too long";
		    BEGIN(STRING_RECOVER);
		    return (ERROR);
		  }
       	          while ( *tmp_ptr )
                    *string_buf_ptr++ = *tmp_ptr++; 
                }
	YY_BREAK


case 53:
YY_RULE_SETUP
#line 287 "cool.flex"
{
	  /* saw closing quote - done with that overly long string */
          BEGIN(INITIAL); /* Continue normally */
        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 292 "cool.flex"
{
	  /* end of line while looking for end of overly long string */
	  /* Now we assume that second double quote is missing. */
	  curr_lineno++;
	  BEGIN(INITIAL); /* just continue in normal mode. */
        }
	YY_BREAK
case YY_STATE_EOF(STRING_RECOVER):
#line 299 "cool.flex"
{
	  /* End of file while recovering from overly long string */
	  yyterminate();
        }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 304 "cool.flex"
{ /* Need not do anything */ }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 305 "cool.flex"
{ curr_lineno++; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 307 "cool.flex"
{ /* Need not do anything */ } 
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 309 "cool.flex"
{ /* backslash at end of file in recovery, ignore */ }
	YY_BREAK

case 59:
YY_RULE_SETUP
#line 313 "cool.flex"
{ bad_char_buf[0] = yytext[0];
			  yylval.error_msg = bad_char_buf;
			  return ERROR; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 317 "cool.flex"
{ yyterminate(); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 319 "cool.flex"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1311 "cool-lex.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 53);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 187 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 53;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 187 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 186);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 319 "cool.flex"

